language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ] ; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot ;
    fi
  - if [ "$EMACS" = 'emacs24' ] ; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg ;
    fi
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
  - pip install jedi --use-mirrors
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2.6 ]] ; then
      pip install unittest2 --use-mirrors ;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]] ; then
      pip install rope --use-mirrors ;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.* ]] ; then
      pip install rope_py3k --use-mirrors ;
    fi
script:
  - nosetests
  - PYTHONPATH="`pwd`" cask exec ert-runner
