language: python
sudo: no
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  # - EVM_EMACS=emacs-24.1-travis
  # - EVM_EMACS=emacs-24.2-travis
  # - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  # - EVM_EMACS=emacs-git-snapshot
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask --verbose        # verbose only needed because of cask bug
install:
  - pip install jedi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2.6 ]] ; then
      pip install unittest2 ;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2.* ]] ; then
      pip install rope ;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.* ]] ; then
      pip install rope_py3k ;
    fi
  - pip install autopep8
  - pip install yapf
  - if [[ "$TRAVIS_PYTHON_VERSION" > 3.6 || "$TRAVIS_PYTHON_VERSION" == 3.6 ]] ; then
      pip install black ;
    fi
  - pip install coveralls
script:
  - nosetests
  - PYTHONPATH="`pwd`" cask exec ert-runner
after_success:
  - coverage run -m nose.__main__
  - coveralls
