language: python
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
install:
  - "pip install nose rope jedi --use-mirrors"
python:
  - "2.7"
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  ./test-travis.sh
